PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "SignatureDomain_province" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(15) NOT NULL);
INSERT INTO "SignatureDomain_province" VALUES(1,'Copperbelt');
INSERT INTO "SignatureDomain_province" VALUES(2,'Central');
INSERT INTO "SignatureDomain_province" VALUES(3,'Eastern');
INSERT INTO "SignatureDomain_province" VALUES(4,'Luapula');
INSERT INTO "SignatureDomain_province" VALUES(5,'Lusaka');
INSERT INTO "SignatureDomain_province" VALUES(6,'Muchinga');
INSERT INTO "SignatureDomain_province" VALUES(7,'Northern');
INSERT INTO "SignatureDomain_province" VALUES(8,'North Western');
INSERT INTO "SignatureDomain_province" VALUES(9,'Southern');
INSERT INTO "SignatureDomain_province" VALUES(10,'Western');
COMMIT;
