# Generated by Django 2.0.2 on 2018-02-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhis2_uid', models.CharField(blank=True, max_length=13, null=True)),
                ('HMIS_Code', models.CharField(max_length=8)),
                ('facility_name', models.CharField(max_length=30)),
                ('number_of_beds', models.IntegerField(blank=True, null=True)),
                ('number_of_cots', models.IntegerField(blank=True, null=True)),
                ('number_of_nurses', models.IntegerField(blank=True, null=True)),
                ('number_of_doctors', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_address', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('fax', models.CharField(blank=True, max_length=13, null=True)),
                ('street_name', models.CharField(blank=True, max_length=30, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('area_name', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=10, null=True)),
                ('catchment_population', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('star', models.TextField(blank=True, max_length=1000, null=True)),
                ('rated', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.TextField(blank=True, max_length=10, null=True)),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.AdministrativeUnit')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.District')),
                ('equipment', models.ManyToManyField(blank=True, to='MFL.Equipment')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Infrastructure',
            },
        ),
        migrations.CreateModel(
            name='LabLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Lab Levels',
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Operating Hours',
            },
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Operational status',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ownership',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.FacilityType'),
        ),
        migrations.AddField(
            model_name='facility',
            name='infrastructure',
            field=models.ManyToManyField(blank=True, to='MFL.Infrastructure'),
        ),
        migrations.AddField(
            model_name='facility',
            name='lab_level',
            field=models.ManyToManyField(to='MFL.LabLevel'),
        ),
        migrations.AddField(
            model_name='facility',
            name='operating_hours',
            field=models.ManyToManyField(to='MFL.OperatingHours'),
        ),
        migrations.AddField(
            model_name='facility',
            name='operational_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.OperationalStatus'),
        ),
        migrations.AddField(
            model_name='facility',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.Ownership'),
        ),
        migrations.AddField(
            model_name='facility',
            name='services',
            field=models.ManyToManyField(to='MFL.Service'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.Province'),
        ),
    ]
