# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='infrastructure',
            field=models.ManyToManyField(blank=True, to='MFL.Infrastructure'),
        ),
    ]
