# Generated by Django 2.0.2 on 2018-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
