# Generated by Django 2.0.2 on 2018-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFL', '0002_auto_20180228_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
