# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFL', '0002_auto_20170712_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
