# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFL', '0003_facility_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='MFL.Equipment'),
        ),
    ]
