# Generated by Django 2.0.2 on 2018-05-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MFL', '0004_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='MFL.ServiceCategory'),
            preserve_default=False,
        ),
    ]
