# Generated by Django 2.2.1 on 2019-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
