# Generated by Django 2.1.2 on 2018-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20181227_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='area_sq_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Land area, sq. km'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='pop_density',
            field=models.FloatField(blank=True, null=True, verbose_name='People per sq. km'),
        ),
        migrations.AlterField(
            model_name='district',
            name='area_sq_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Land area, sq. km'),
        ),
        migrations.AlterField(
            model_name='district',
            name='pop_density',
            field=models.FloatField(blank=True, null=True, verbose_name='People per sq. km'),
        ),
        migrations.AlterField(
            model_name='province',
            name='area_sq_km',
            field=models.FloatField(verbose_name='Land area, sq. km'),
        ),
        migrations.AlterField(
            model_name='province',
            name='pop_density',
            field=models.FloatField(verbose_name='People per sq. km'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='area_sq_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Land area, sq. km'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='pop_density',
            field=models.FloatField(blank=True, null=True, verbose_name='People per sq. km'),
        ),
    ]
